# Generated by Django 4.1.5 on 2023-02-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_toppost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
